name: E2E Tests

on:
  pull_request:
    branches:
      - Develop
      - Staging

jobs:
  test:
    name: E2E Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21.x

      - name: Install dependencies
        run: npm install

      - name: Run E2E Tests
        run: npm run test-e2e

      - name: Upload Cypress Artifacts (On Failure)
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: cypress-screenshots
          path: cypress/screenshots